export { default as Dashboard } from "./Dashboard";
export { default as MyProfile } from "./MyProfile";
export { default as MyProfileEdit } from "./MyProfileEdit";
export { default as Logout } from "./Logout";
export { default as Login } from "./Login";
export { default as ForgetPassword } from "./ForgetPassword";
export { default as ResetPassword } from "./ResetPassword";
export { default as MyProfileChangePassword } from "./MyProfileChangePassword";
export { default as NotFound404 } from "./NotFound404";
