export const CONSTANTS = {
  VITE_USER_SITE_BASE_URL: import.meta.env.VITE_USER_SITE_BASE_URL,
  VITE_BACKEND_STATIC_URL: import.meta.env.VITE_BACKEND_STATIC_URL,
  VITE_BACKEND_STATIC_URL_FOR_FILE: import.meta.env.VITE_BACKEND_STATIC_URL_FOR_FILE,
  VITE_BACKEND_API_URL: import.meta.env.VITE_BACKEND_API_URL,
  VITE_BACKEND_SUBSCRIPTION_EXPORT_URL: import.meta.env
    .VITE_BACKEND_SUBSCRIPTION_EXPORT_URL,
};
